"""update_field_db

Revision ID: 2907b51ffbe4
Revises: 116c0e7e8dc6
Create Date: 2026-01-19 20:48:12.396705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2907b51ffbe4'
down_revision: Union[str, Sequence[str], None] = '116c0e7e8dc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('literature_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'literature_score')
    # ### end Alembic commands ###
