"""update_fields

Revision ID: cf3ee0980c2e
Revises: 2907b51ffbe4
Create Date: 2026-01-19 22:01:07.619016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf3ee0980c2e'
down_revision: Union[str, Sequence[str], None] = '2907b51ffbe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('literature_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'literature_score')
    # ### end Alembic commands ###
